backend:
  name: git-gateway
  branch: main # Thay đổi "main" thành nhánh mà bạn đang sử dụng trong repo của mình

media_folder: "images" # Thư mục nơi các tệp media (như hình ảnh) sẽ được lưu
public_folder: "/images" # Đường dẫn công khai tới các tệp media

collections:
  - name: "introduction"
    label: "Giới Thiệu"
    folder: "content/introduction"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }

  - name: "attractions"
    label: "Địa Điểm Tham Quan"
    folder: "content/attractions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "gallery"
    label: "Thư Viện Ảnh"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Images", name: "images", widget: "list", field: { name: "image", widget: "image" } }

  - name: "contact"
    label: "Liên Hệ"
    folder: "content/contact"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
