backend:
  name: git-gateway
  branch: main # Thay đổi theo branch mà bạn đang sử dụng trong kho lưu trữ Git của bạn

media_folder: "images" # Thư mục để lưu trữ các tệp media
public_folder: "/images" # Đường dẫn công khai tới các tệp media

collections:
  - name: "introduction"
    label: "Giới Thiệu"
    folder: "content/introduction" # Thư mục lưu trữ nội dung Giới Thiệu
    create: true
    slug: "giới-thiệu"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }

  - name: "attractions"
    label: "Địa Điểm Tham Quan"
    folder: "content/attractions" # Thư mục lưu trữ nội dung Địa Điểm Tham Quan
    create: true
    slug: "{{slug}}" # Tạo slug từ tiêu đề
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "gallery"
    label: "Thư Viện Ảnh"
    folder: "content/gallery" # Thư mục lưu trữ các ảnh thư viện
    create: true
    slug: "thư-viện-ảnh"
    fields:
      - { label: "Images", name: "images", widget: "list", field: 
          { name: "image", widget: "image" } 
        }

  - name: "contact"
    label: "Liên Hệ"
    folder: "content/contact" # Thư mục lưu trữ nội dung Liên Hệ
    create: true
    slug: "liên-hệ"
    fields:
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
